### ISSUE TITLE
G4 open issues

### ISSUE THREAD

**Issue by heben2** [Pilen/sdsa#11]
- [x] Redfine functional view. HB
- [x] Redfine functional scenarios to be consistent with functional view.
- [x] 5.3 Information view - @heben2
- [x] 5.4 Concurrency view @Pilen 
- [x] 5.6 Development view @nwillems

**Comment by nwillems** [comment]
Hey guys.

Sektion 5.6 handler om development - og det stemmer overens med opgavens beskrivelse på Absalon.
Så jeg tager mig af noget udviklings metodik :-)

**Comment by nwillems** [comment]
Request For review of `Development view` mainly in commit 1c6d2e6d8d0b58af1ff94f8bea376117195b0144

**Comment by nwillems** [comment]
Closing - opgaven sat som tilfredsstillende.
