### ISSUE TITLE
Valg af værktøj til opførsel af prototype

### ISSUE THREAD

**Issue by nwillems** [Pilen/sdsa#2]
Skal vi også bruge Java til vores prototype? Eller skal vi gøre det i noget mere eksotisk?

**Comment by nwillems** [comment]
Democrazy??

**Comment by heben2** [comment]
Prolog

**Comment by heben2** [comment]
og notepad

**Comment by nwillems** [comment]
Javascript

**Comment by heben2** [comment]
på dos

**Comment by nwillems** [comment]
Mener du sod?

**Comment by Pilen** [comment]
Nej, vi laver vores eget styresystem, og kalder det dos

**Comment by nwillems** [comment]
Hvad med at lave det på z/OS?

**Comment by Pilen** [comment]
Det skal i scope, et nyt styresystem.

**Comment by nwillems** [comment]
+1

**Comment by Pilen** [comment]
- et chatsystem bygget over et issuesystem
- En ny mappedatamat til Nicolai - den giver jeg

**Comment by nwillems** [comment]
Det lyder som en rigtig god ide. Skal vi f.eks. bruge Bugzilla i bunden?
nej

**Comment by Pilen** [comment]
nah, det kan nok ikke køre på vores styresystem

**Comment by nwillems** [comment]
Bugzilla er skrevet i Perl - det skal nok køre

**Comment by Pilen** [comment]
Fuck, så skal vi lave en perloversætter til vores styresystem!

**Comment by nwillems** [comment]
:dancer: :-1:  :facepunch:
