### ISSUE TITLE
Opgaver til G2

### ISSUE THREAD

**Issue by nwillems** [Pilen/sdsa#5]
- [ ] Fill out remaining stakeholder-table
- [x] Validate "Overview of requirements"
- [ ] Flesh out on "Overview of requirements"
- [x] Scenarios - functional - Nicolai
- [x] Scenarios - Quality - Nicolai

Left over from G1
- [x] Context View/Diagram - Pilen
- [x] Section 5.1.2 - interaction scenarios

**Comment by nwillems** [comment]
Hvem tager sig af at få udfyldt den resterende Interesent tabel?

**Comment by nwillems** [comment]
Så er der scenarier - 0f8f99bee7515fb2ea19e9b089647e74d1422fd6

**Comment by heben2** [comment]
Cool, jeg læser dem lige igennem.

Jeg fuckede up i min branch (er ikke så sej til git), men håber det er fikset nu --  Nicolai, du har kun tilføjet til scenarier, ikke? Bare så jeg ikke kommer til at slette ting du har lavet.

Jeg skal nok se på resten af stakeholder-tabellen; den havde jeg allerede lavet flere på.

**Comment by nwillems** [comment]
Jo, det er kun scenarier. Du kan evt trykke på commitet her på issuet, og se en diff af hvad der er lavet.

**Comment by heben2** [comment]
Right, det havde jeg ikk tænkt på.. Men super.

**Comment by heben2** [comment]
Jeg har nu udfyldt de sidste stakeholders. Hvis nogen har tid/lyst, må de meget gerne lige læses igennem.
